### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by MinhPhu0304** [rusq/mtpwrap#1]
Could you add more documentation on this please. 🥺 

:rustam-galaxy-brain:

**Comment by rusq** [comment]
Sure! send 0.1 BTC to this addr: 15gfz6DqzB99xhhvVNfVtYcTZi1wWqKrjb, and I'll add some doc

**Comment by MinhPhu0304** [comment]
Now that is a rip off, 1/5 star

**Comment by rusq** [comment]
That's good news, it could be 0/5 stars!
